### ISSUE TITLE
Possible UI improvement on how the News List displays links

### ISSUE THREAD

**Issue by liquiddandruff** [sfu-fas/coursys#93]
Might just be me, but I never knew that we could go directly to the marks page from the latest news section because the links are the same colour. 

Making the colours different like this might be a possible solution.

```css
div#newsitems a.collapsible-heading-toggle {
	color: #000;	
}

```
## Before
![after](https://i.imgur.com/KpaMOZB.png)

## After
![after](https://i.imgur.com/qb41CQ9.png)
